# Generated by Django 5.2.4 on 2025-08-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID_USUARIO', models.AutoField(primary_key=True, serialize=False)),
                ('NOME', models.CharField(default='Unkno', max_length=255)),
                ('EMAIL', models.EmailField(max_length=255, unique=True)),
                ('PASSWORD', models.CharField(max_length=255)),
                ('TIPO_USUARIO', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('ID_PEDIDO', models.AutoField(primary_key=True, serialize=False)),
                ('DATA_EFETUADO', models.DateField(auto_now_add=True)),
                ('STATUS', models.CharField(default='Pendente', max_length=50)),
                ('DATA_CONCLUIDO', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('ID_PRODUTO', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('condicao', models.CharField(blank=True, max_length=255, null=True)),
                ('detalhes_condicao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produto_virtual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('ID_STOCK', models.AutoField(primary_key=True, serialize=False)),
                ('ID_PRODUTO', models.IntegerField()),
                ('QUANTIDADE', models.IntegerField()),
                ('ULTIMO_UPDATE', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tem2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_PRODUTO', models.IntegerField()),
                ('QUANTIDADE', models.IntegerField()),
            ],
            options={
                'db_table': 'tem2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ID_CLIENTE', models.OneToOneField(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loja.usuario')),
                ('GENERO', models.CharField(blank=True, max_length=20, null=True)),
                ('DATA_NASCIMENTO', models.DateField(blank=True, null=True)),
                ('MORADA', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('ID_FORNECEDOR', models.OneToOneField(db_column='id_fornecedor', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='loja.usuario')),
                ('NIF', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'fornecedor',
                'managed': False,
            },
        ),
    ]
