# Generated by Django 5.1.6 on 2025-02-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido',
            table='pedido',
        ),
        migrations.AlterModelTable(
            name='pedidoproduto',
            table='pedido_produto',
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produto',
        ),
        migrations.AlterModelTable(
            name='promocao',
            table='promocao',
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
