# Generated by Django 5.2.4 on 2025-09-01 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produto',
            table=None,
        ),
    ]
