# Generated by Django 5.1.6 on 2025-02-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_alter_pedido_table_alter_pedidoproduto_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='categoria',
            new_name='CATEGORIA',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='condicao',
            new_name='CONDICAO',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='marca',
            new_name='MARCA',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='NOME',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='PRECO',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='detalhes_condicao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='id',
        ),
        migrations.AddField(
            model_name='produto',
            name='ID_PRODUTO',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='produto',
            table=None,
        ),
        migrations.AddField(
            model_name='produto',
            name='DESCRICAO',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='DETALHES_CONDICAO',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
