# Generated by Django 5.1.6 on 2025-02-11 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_rename_categoria_produto_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='CATEGORIA',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='CONDICAO',
            new_name='condicao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='DESCRICAO',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='DETALHES_CONDICAO',
            new_name='detalhes_condicao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='MARCA',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='NOME',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='PRECO',
            new_name='preco',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pedidoproduto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='promocao',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='pedido',
            name='ID_PEDIDO',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoproduto',
            name='ID_PEDIDO_PRODUTO',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocao',
            name='ID_PROMOCAO',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='ID_STOCK',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='ID_USUARIO',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='loja.usuario'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_produtos', to='loja.pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_produtos', to='loja.produto'),
        ),
        migrations.AlterField(
            model_name='promocao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='loja.produto'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='loja.produto'),
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produto',
        ),
    ]
