# Generated by Django 5.1.6 on 2025-02-11 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_rename_categoria_produto_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='ID_PEDIDO',
            new_name='id_pedido',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='ID_PRODUTO',
            new_name='id_produto',
        ),
        migrations.RenameField(
            model_name='promocao',
            old_name='ID_PROMOCAO',
            new_name='id_promocao',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='ID_STOCK',
            new_name='id_stock',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='ID_USUARIO',
            new_name='id_usuario',
        ),
    ]
