# Generated by Django 5.1.6 on 2025-02-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_rename_id_pedido_pedido_id_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='id_pedido',
            new_name='ID_PEDIDO',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='id_produto',
            new_name='ID_PRODUTO',
        ),
        migrations.RenameField(
            model_name='promocao',
            old_name='id_promocao',
            new_name='ID_PROMOCAO',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='id_stock',
            new_name='ID_STOCK',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuario',
            new_name='ID_USUARIO',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='PEDIDO',
        ),
    ]
