DROP TABLE IF EXISTS TEM2 CASCADE;
DROP TABLE IF EXISTS STOCK CASCADE;
DROP TABLE IF EXISTS PEDIDO CASCADE;
DROP TABLE IF EXISTS CLIENTE CASCADE;
DROP TABLE IF EXISTS FORNECEDOR CASCADE;
DROP TABLE IF EXISTS USUARIO CASCADE;
DROP SEQUENCE IF EXISTS produto_id_seq CASCADE;

CREATE SEQUENCE produto_id_seq START 16;

CREATE TABLE USUARIO (
    ID_USUARIO SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    TIPO_USUARIO VARCHAR(20) NOT NULL
);

CREATE TABLE CLIENTE (
    ID_CLIENTE INT PRIMARY KEY,
    GENERO VARCHAR(20),
    DATA_NASCIMENTO DATE,
    MORADA VARCHAR(255),
    FOREIGN KEY (ID_CLIENTE) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE FORNECEDOR (
    ID_FORNECEDOR INT PRIMARY KEY,
    NIF VARCHAR(20),
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE
);

CREATE TABLE PEDIDO (
    ID_PEDIDO SERIAL PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    DATA_EFETUADO DATE NOT NULL DEFAULT CURRENT_DATE,
    STATUS VARCHAR(50) NOT NULL DEFAULT 'Pendente',
    DATA_CONCLUIDO DATE,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);

CREATE TABLE STOCK (
    ID_STOCK SERIAL PRIMARY KEY,
    ID_FORNECEDOR INT NOT NULL,
    ID_PRODUTO INT NOT NULL, -- ref a Produto no Mongo
    QUANTIDADE INT NOT NULL CHECK (QUANTIDADE >= 0),
    ULTIMO_UPDATE DATE NOT NULL DEFAULT CURRENT_DATE,
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR) ON DELETE CASCADE
);

CREATE TABLE TEM2 (
    ID_PEDIDO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL CHECK (QUANTIDADE > 0),
    PRIMARY KEY (ID_PEDIDO, ID_PRODUTO),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO) ON DELETE CASCADE
);
