CREATE ROLE AdministradorSite WITH LOGIN PASSWORD 'pass';
CREATE ROLE app_manager WITH LOGIN PASSWORD 'manager_pass';
CREATE ROLE regular_user WITH LOGIN PASSWORD 'user_pass';

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO AdministradorSite;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO AdministradorSite;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_manager;

GRANT SELECT ON STOCK, PEDIDO TO regular_user;
GRANT INSERT ON PEDIDO, TEM2 TO regular_user;

REVOKE ALL ON CLIENTE, FORNECEDOR, USUARIO FROM regular_user;